---
title: Acidification
---

Acidification (again), what it does, organisms impacted.
[Derek Manzello](https://www.aoml.noaa.gov/about_us/staff/index.html?lname=MANZELLO&fname=Derek) studies.
TODO: CK will follow-up.

highlight one study

* pH
* OA
* calcification

Climate change impacts: acidification is poorly understood by public, loss of ecosystem services due to combined impacts.

Story of acidification impacts:

* [Ocean Acidification | Smithsonian Ocean]( https://ocean.si.edu/ocean-life/invertebrates/ocean-acidification )
* [What is Ocean Acidification? | pmel.noaa.gov]( https://www.pmel.noaa.gov/co2/story/What+is+Ocean+Acidification%3F )
* [What is Ocean Acidification? | oceanservice.noaa.gov](https://oceanservice.noaa.gov/facts/acidification.html  )
* [oceanhealthindex.org/../ocean-acidification](  http://www.oceanhealthindex.org/methodology/components/ocean-acidification)
* [Ocean Acidification Around the World]( https://noaa.maps.arcgis.com/apps/MapTour/index.html?appid=1c33c6304fb9466a9185adb0d12a4e7c )


Loss of coastal protection from natural defenses: https://coastalresilience.org/project/natural-defense-projects/
https://snappartnership.net/teams/coastal-defenses/


TODO: Reef calcification (erosion-accretion): Ilsa Kuffner data (USGS)

Buffers are provided by seagrass, mangrove.

* [Indirect effects may buffer negative responses of seagrass invertebrate communities to ocean acidification - ScienceDirect](https://www.sciencedirect.com/science/article/pii/S0022098114001993)
* [Expected limits on the ocean acidification buffering potential of a temperate seagrass meadow - Koweek - 2018 - Ecological Applications - Wiley Online Library](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/eap.1771)
* [Biophysical feedbacks mediate carbonate chemistry in coastal ecosystems across spatiotemporal gradients | Scientific Reports](https://www.nature.com/articles/s41598-017-18736-6)
* [Seagrass can mitigate negative ocean acidification effects on calcifying algae | Scientific Reports](https://www.nature.com/articles/s41598-018-35670-3)


[oceanacidification.noaa](https://oceanacidification.noaa.gov/WhatWeDo/Data.aspx)

[pmel.noaa](https://www.pmel.noaa.gov/co2/story/Cheeca+Rocks)
